import { useState, useEffect } from 'react';
import { FileText, Download, Loader2 } from 'lucide-react';
import { getSessions, generateReport, getReports } from '../services/api';

export default function Reports() {
  const [sessions, setSessions] = useState([]);
  const [reports, setReports] = useState([]);
  const [generating, setGenerating] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const [sessRes, repRes] = await Promise.all([
        getSessions(),
        getReports(),
      ]);
      setSessions(sessRes.data.filter((s) => s.status === 'completed'));
      setReports(repRes.data);
    } catch (e) {
      console.error('Failed to load data:', e);
    }
    setLoading(false);
  };

  const handleGenerate = async (sessionId) => {
    setGenerating(sessionId);
    try {
      await generateReport(sessionId);
      await loadData();
    } catch (e) {
      console.error('Failed to generate report:', e);
    }
    setGenerating(null);
  };

  return (
    <div className="animate-in">
      <div className="page-header">
        <h1>Reports</h1>
        <p>Generate and download PDF reports from completed analysis sessions</p>
      </div>

      {/* Generate Reports */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div className="card-header">
          <span className="card-title">Generate Report</span>
        </div>

        {sessions.length === 0 ? (
          <div className="empty-state">
            <FileText size={48} />
            <h3>No Completed Sessions</h3>
            <p>Run a simulation or upload a PCAP file first to create a session.</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Session</th>
                <th>Type</th>
                <th>Packets</th>
                <th>Windows</th>
                <th>Completed</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {sessions.map((s) => (
                <tr key={s.id}>
                  <td style={{ color: 'var(--text-primary)' }}>{s.name}</td>
                  <td style={{ textTransform: 'uppercase' }}>{s.source_type}</td>
                  <td>{s.packet_count?.toLocaleString()}</td>
                  <td>{s.flow_count}</td>
                  <td>{s.completed_at ? new Date(s.completed_at).toLocaleString() : '—'}</td>
                  <td>
                    <button
                      className="btn btn-primary btn-sm"
                      onClick={() => handleGenerate(s.id)}
                      disabled={generating === s.id}
                    >
                      {generating === s.id ? (
                        <><Loader2 size={14} className="loading-pulse" /> Generating...</>
                      ) : (
                        <><FileText size={14} /> Generate PDF</>
                      )}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Report History */}
      <div className="card">
        <div className="card-header">
          <span className="card-title">Report History</span>
        </div>

        {reports.length === 0 ? (
          <div className="empty-state">
            <p>No reports generated yet</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Session</th>
                <th>Size</th>
                <th>Generated By</th>
                <th>Created</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id}>
                  <td style={{ color: 'var(--text-primary)' }}>#{r.id}</td>
                  <td>Session #{r.session_id}</td>
                  <td>{r.file_size_bytes ? `${(r.file_size_bytes / 1024).toFixed(1)} KB` : '—'}</td>
                  <td>{r.generated_by || '—'}</td>
                  <td>{new Date(r.created_at).toLocaleString()}</td>
                  <td>
                    <a
                      href={`/api/reports/${r.id}/download`}
                      className="btn btn-secondary btn-sm"
                      download
                    >
                      <Download size={14} /> Download
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
